name: Build and push docker images

on:
  push:
    branches:
      - master
      - main
    paths:
      - '.github/workflows/*'
      - '.github/*'
      - 'src/Dockerfile*'
      - 'src/rootfs/*'
      - 'src/hook/*'
      - 'src/VERSIONS'
      - 'src/*.sh'
      - 'src/VERSIONS'
      - 'tests/**'
  pull_request:
    branches:
      - master
      - main
    paths:
      - '.github/workflows/*'
      - '.github/*'
      - 'src/Dockerfile'
      - 'src/rootfs/*'
      - 'src/hook/*'
      - 'src/*.sh'
      - 'src/VERSIONS'
      - 'tests/**'

jobs:
  build:
    name: Build and push image to dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub Registry
        run: |
          echo  ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: s6v3. Build and push images
        run: |
          cd ${GITHUB_WORKSPACE}/src/hook
          ./build.sh
          ./push.sh

      - name: s6v2. Build and push images
        run: |
          cd ${GITHUB_WORKSPACE}/src/hook
          export S6_OVERLAY_VERSION='2.2.0.3'
          export S6_OVERLAY_IMAGE_TAG='2.2.0.3'
          export DOCKERFILE='Dockerfile.s6v2'
          ./build.sh
          ./push.sh
